blueprint: page

title: Item de ressource
icon: tag

options:
  delete: false

columns:
  main:
    width: 1/1
    sections:
      content:
        type: fields
        fields:
          subtitle:
            type: text
            label: Sous-titre

          authors:
            type: text
            label: Auteurs

          source:
            type: url
            label: Source

#          todo: catégorie de ressource, qui peut "Articles, Video, Podcast, Papier Académique"
          description:
            type: writer
            label: Description
            inline: true
            nodes:
              - paragraph
            marks:
              - italic

          file:
            type: files
            label: Fichier (PDF)
            multiple: false
            query: page.files.filterBy('extension', 'pdf')
            uploads:
              template: pdf
