blueprint: page

title: Item de ressource
icon: tag

options:
  delete: false

columns:
  main:
    width: 1/1
    sections:
      content:
        type: fields
        fields:
          subtitle:
            type: text
            label: Sous-titre

          authors:
            type: text
            label: Auteurs

          source:
            type: url
            label: Source

#          todo: catégorie de ressource, qui peut "Articles, Video, Podcast, Papier Académique"
          description:
            type: writer
            label: Description
            inline: true
            nodes:
              - paragraph
            marks:
              - italic

          file:
            type: files
            label: Fichier (PDF)
            multiple: false
            query: page.files.filterBy('extension', 'pdf')
            uploads:
              template: pdf

      keywords_section:
        type: fields
        fields:
          themes:
            type: pages
            label: Thèmes
            help: Mots-clés gérés dans les réglages du site
            query: site.find('themes').children.filterBy('intendedTemplate', 'tag')
          concepts:
            type: pages
            label: Concepts
            help: Mots-clés gérés dans les réglages du site
            query: site.find('concepts').children.filterBy('intendedTemplate', 'tag')
          platforms:
            type: pages
            label: Plateformes
            help: Mots-clés gérés dans les réglages du site
            query: site.find('platforms').children.filterBy('intendedTemplate', 'tag')
          questions:
            type: pages
            label: Questions
            help: Mots-clés gérés dans les réglages du site
            query: site.find('question').children.filterBy('intendedTemplate', 'tag')
