blueprint: page

title: Site Infos

columns:
  main:
    width: 2/3
    sections:
      header:
        type: fields
        fields:
          sentences:
            type: structure
            label: Liste de titres
            fields:
              sentence:
                type: text

          header_subtitle:
            type: writer
            label: Sous-titre
            inline: true
            marks: false

      infos:
        type: fields
        fields:
          long_description:
            type: writer
            label: Description courte
            inline: true
            marks: false

          informations:
            type: writer
            label: Texte d'information défilent
            inline: true
            marks: false
