blueprint: page

title: Site Infos

columns:
  main:
    width: 2/3
    sections:
      header:
        type: fields
        fields:
          sentences:
            type: structure
            label: Liste de titre
            fields:
              sentence:
                type: text

          header_subtitle:
            type: writer
            label: Sous-titre
            inline: true
            nodes:
              - paragraph
            marks:
              - italic

      infos:
        type: fields
        fields:
          long_description:
            type: writer
            label: Description longue
            nodes:
              - paragraph
            marks:
              - italic
