blueprint: page

title: Thématique
icon: tag

options:
  delete: false

columns:
  main:
    width: 1/1
    sections:
      image:
        type: fields
        fields:
          image:
            extends: fields/image
