blueprint: page

title: Item de la thématique
icon: tag

options:
  delete: false

columns:
  main:
    width: 1/1
    sections:
      image:
        type: fields
        fields:
          image:
            extends: fields/image
            multiple: true
          description:
            type: writer
            label: Définition
            inline: true
            nodes:
              - paragraph
            marks:
              - italic
