blueprint: page

title: Site Infos

columns:
  main:
    width: 2/3
    sections:
      image:
        type: fields
        fields:
          description:
            type: writer
            label: Déscription
            nodes:
              - paragraph
            marks:
              - italic

          image:
            extends: fields/image
            layout: cards
            size: large


          url:
            label: URL
            type: url
