blueprint: block
name: Cartels
icon: tag
preview: fields
wysiwyg: true

fields:
  cards:
    type: structure
    fields:
      title:
        type: writer
        label: Titre
        inline: true
        width: 1/2
        nodes:
          - paragraph
        marks:
          - italic
        help: Titre de la section

      tags:
        type: tags
        label: Tags

      description:
        type: writer
        label: Description
