blueprint: block
name: Citation
icon: quote
preview: fields
wysiwyg: true

fields:
  title:
    type: writer
    label: Titre
    inline: true
    width: 1/2
    nodes:
      - paragraph
    marks:
      - italic
    help: Titre de la section
  contenu:
    type: writer
    label: Contenu
  signature:
    type: text
    label: Signature (auteur·ice·x)
