blueprint: block
name: Formations
icon: globe
preview: fields
wysiwyg: true

fields:
  help:
    type: info
    text: Ce block ne contient aucun champ éditable. Il sert uniquement de point d'ancrage pour afficher dynamiquement le composant "formations" en front.
