blueprint: block
name: Formulaire
icon: check
preview: fields
wysiwyg: true

fields:
  title:
    type: writer
    label: Titre
    inline: true
    width: 1/2
    nodes:
      - paragraph
    marks:
      - italic
    help: Titre de la section


  form_type :
    type: select
    label: Type de formulaire
    options:
        - value: inscription
          text: formulaire d'inscription
        - value: contact
          text: formulaire de contact

  help:
    type: info
    text: Ce block ne contient aucun champ éditable. Il sert uniquement de point d'ancrage pour afficher dynamiquement le composant "formulaire" en front.
