blueprint: block
name: Formations
icon: globe
preview: fields
wysiwyg: true

fields:
  title:
    type: writer
    label: Titre
    inline: true
    width: 1/2
    nodes:
      - paragraph
    marks:
      - italic
    help: Titre de la section

  help:
    type: info
    text: Ce block ne contient aucun champ éditable. Il sert uniquement de point d'ancrage pour afficher dynamiquement le composant "formations" en front.
