blueprint: block

name: Formulaire

icon: check

fields:
  form_type :
    type: select
    label: Type de formulaire
    options:
        - value: inscription
          text: formulaire d'inscription
        - value: contact
          text: formulaire de contact

  help:
    type: info
    text: Ce block ne contient aucun champ éditable. Il sert uniquement de point d'ancrage pour afficher dynamiquement le composant "formulaire" en front.
