blueprint: block
name: Gallery
icon: images
preview: fields
wysiwyg: true

fields:
  items:
    label: Items
    type: structure
    fields:
      title:
        label: Titre
        type: text
      content:
        label: Contenu
        type: writer
        inline: true
        nodes:
          - paragraph
        marks:
          - italic
      image:
        label: Image
        type: files
        multiple: false
        query: page.images
        uploads: true
      link:
        label: Lien
        type: url
