blueprint: block
name: Partenaires
icon: bluesky
preview: fields
wysiwyg: true

fields:
  cards:
    type: structure
    fields:
      title:
        type: writer
        label: Titre
        inline: true
        width: 1/2
        nodes:
          - paragraph
        marks:
          - italic
        help: Titre de la section

      description:
        type: writer
        label: Description

      partners:
        type: structure
        label: Liste des partenaires
        fields:
          name:
            type: text
            label: Nom
          logo:
            extends: fields/image
            label: Logo
