blueprint: block
name: Enseignant·e·xs & Responsable·xs
icon: users
preview: fields
wysiwyg: true

fields:
  teacher_pages:
    type: pages
    label: Enseignant·e·xs & Responsable·xs
    query: site.index.filterBy("intendedTemplate", "teacher")
    multiple: true
