blueprint: block
name: Contenu texte
icon: text
preview: fields
wysiwyg: true

fields:
  title:
    type: writer
    label: Titre
    inline: true
    width: 1/2
    nodes:
      - paragraph
    marks:
      - italic
    help: Titre de la section

  text:
    label: Texte
    type: writer
    inline: false
    nodes:
      - paragraph
      - bulletList
    marks:
      - italic
    placeholder: field.blocks.text.placeholder
