blueprint: block
name: Contenu texte
icon: text
preview: fields
wysiwyg: true

fields:
  text:
    label: Texte
    type: writer
    inline: false
    nodes:
      - paragraph
      - bulletList
    marks:
      - italic
    placeholder: field.blocks.text.placeholder
