blueprint: site

title: Site


columns:
  - width: 1/4
    sections:
      infos:
        label: Informations Génarales
        help: Informations générales sur le site
        image: false
        layout: cards
        type: pages
        template: site_infos

      teachers:
        label: Enseignant·e·xs & Responsable·xs
        image: false
        layout: cards
        type: pages
        template: teachers

      temoignages:
        label: Témoignages / Alumni
        image: false
        layout: cards
        type: pages
        template: testimonials

      events:
        label: Événements
        layout: cards
        type: pages
        template: events



  - width: 3/4
    sections:
      pages:
        label: Pages
        layout: cards
        type: pages
        template: default

  - width: 1/4
    fields:
      gap: true
