blueprint: site

title: Site


columns:
  - width: 1/4
    sections:
      infos:
        label: Informations Génarales
        help: Informations générales sur le site
        image: false
        layout: cards
        type: pages
        template: site_infos

      tools:
        label: Outils
        image: false
        layout: cards
        type: pages
        template: tools


      themes_section:
        type: fields
        fields:
          themes:
            label: Thématiques
            type: structure
            help: >
              Liste des thématiques disponibles pour les pages. On peut en ajouter
              ou modifier le nom, mais une thématique existante ne peut pas être
              supprimée ici.
            columns:
              name:
                label: Nom
            fields:
              name:
                type: text
                label: Nom
                required: true




  - width: 3/4
    sections:
      pages:
        label: Pages
        layout: cards
        type: pages
        template: default

  - width: 1/4
    fields:
      gap: true
